steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:$BUILD_ID', '.']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['run', '$REPO_NAME', '--image=eu.gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:$BUILD_ID','--namespace=$REPO_NAME-$BRANCH_NAME','--port:80', '--replicas=2']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=eu-west1-d'
  - 'CLOUDSDK_CONTAINER_CLUSTER=production'
images: ['eu.gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:$BUILD_ID']
